### ISSUE TITLE
SimpleAnyBlob error in `ConnectionManager::disconnect`

### ISSUE THREAD

**Issue by zztaki** [durner/AnyBlob#10]
When I simply modified `simple.cpp` in `example` dir to get objects from my s3 bucket, I met an error.
```cpp
anyblob: AnyBlob/src/network/connection_manager.cpp:274: void anyblob::network::ConnectionManager::disconnect(int32_t, const anyblob::network::ConnectionManager::TCPSettings*, uint64_t, bool): Assertion `socketIt != _fdSockets.end()' failed.
```
When dubugging, I find we try to find a fd(= -1) in _fdSocks(size = 0) so assert failed.

My setting is 
```cpp
  auto bucketName = "https://s3.eu-north-1.amazonaws.com/<bucket>/";
  auto fileName = <object_name>;
  auto provider = anyblob::cloud::Provider::makeProvider(
      bucketName, https, <myAk>,
      <mySk>, &sendReceiverHandle);
```

If you can help me I will be very grateful! :)

**Comment by zztaki** [comment]
I'm not sure if there won't be other negative effects of doing this, but simply returning directly when fd=-1 is ok for me. :)

**Comment by durner** [comment]
Would you mind attaching gdb to a debug build and give me the stacktrace when this happens. fd=-1 seems like there is no connection or it has been already aborted.

**Comment by zztaki** [comment]
First of all let me apologize for replying so late, I've had a busy two weeks.

Below is my stack information with https provider, when I use s3 prefix, no error seems to occur.

```cpp
(gdb) bt
#0  0x00007ffff6088005 in raise () from /lib64/libc.so.6
#1  0x00007ffff605a894 in abort () from /lib64/libc.so.6
#2  0x00007ffff605a779 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007ffff60808b6 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000377c0c in anyblob::network::ConnectionManager::disconnect (this=0x60c0000007c0, fd=-1, tcpSettings=0x607000000020, bytes=682, forceShutdown=false)
    at AnyBlob/src/network/connection_manager.cpp:304
#5  0x000000000038710c in anyblob::network::HTTPSMessage::execute (this=0x607000006300, connectionManager=...) at AnyBlob/src/network/https_message.cpp:145
#6  0x0000000000363701 in anyblob::network::TaskedSendReceiver::sendReceive (this=0x60d0000001e0, local=true, oneQueueInvocation=true)
    at AnyBlob/src/network/tasked_send_receiver.cpp:289
#7  0x0000000000361c48 in anyblob::network::TaskedSendReceiverHandle::sendReceive (this=0x7fffffffcbe0, local=true, oneQueueInvocation=true)
    at AnyBlob/src/network/tasked_send_receiver.cpp:152
#8  0x00000000002a9572 in anyblob::network::TaskedSendReceiverHandle::processSync (this=0x7fffffffcbe0, oneQueueInvocation=true)
    at AnyBlob/include/network/tasked_send_receiver.hpp:201
#9  0x000000000039cdcc in anyblob::network::Transaction::processSync (this=0x7fffffffcda0, sendReceiverHandle=...) at AnyBlob/src/network/transaction.cpp:41
#10 0x0000000000279a74 in main () at AnyBlob/src/main.cpp:78

**Comment by durner** [comment]
> When I use s3 prefix, no error seems to occur.
I am sorry, your comment just made me aware of a setting issue, I just didn't notice in the first message.

Even if you want to connect to s3 via TLS you need to use the s3:// prefix. You just need to specify during the creation of the provider that you want ssl by setting the second argument to true. 

```
Provider::makeProvider(const string& filepath, bool https, const string& keyId, const string& secret, network::TaskedSendReceiverHandle* sendReceiverHandle)
```

So the bucketname must still be 
```
auto bucketName = "s3://<bucket>:<region>";
```

Maybe some more documentation is needed. Hopefully I find some time in the coming weeks / months to get started writing better user docs.

**Comment by zztaki** [comment]
Thank you for your help! :)
